baseUrl = "https://blog.vhlv.ml"
languageCode = "en-us"
title = "Your site title"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = "Your site subtitle"

[params.logo]
  logoText = "hello friend"
#   or
#
#   path = "/img/your-example-logo.svg"
#   alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"

